# # # # # # # # # # # # #
#   K i k o - p l u s   #
# # # # # # # # # # # # #

# Basic
name:               "Better Tomorrow with Computer Science"

author:
#  facebook:         your-id
#  youtubeUser:      your-id
#  youtubeChannel:   your-id
#  twitter:          your-id
  github:           insujang
#  stackoverflow:    your-id
#  quora:            your-id
  linkedin:         insujang
#  pinterest:        your-id
#  googlePlus:       your-id
#  instagram:        your-id
#  reddit:           your-id
#  medium:           your-id
#  tumblr:           your-id
  email:            insujang.kaist@gmail.com

copyright:
  year:             2017
  name:             Insu Jang

# Google-analytics
google-analytics:
  id:               ""

# Disqus
disqus:
  id:               "insujang"

# URL
url:                "https://insujang.github.io" # the base hostname & protocol for your site
# url:                "http://localhost:4000" # use this url when you develop
baseurl:            "master" # the subpath of your site, e.g. /blog


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           Asia/Seoul
permalink:          /:year-:month-:day/:title/

# Pagination
paginate:           5
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  input:            GFM

# Navigation
nav:
  - name:           "About"
    url:            "/about"
  - name:           "Archive"
    url:            "/archive"
  - name:           "Tags"
    url:            "/tags"
  - name:           "Github"
    url:            "https://insujang.github.io"

# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
gems:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-admin

exclude:            [vendor]
